const CACHE_NAME = "getting-strange-v3-pkg0091";
// Generated by tools/generate_service_worker.js — full offline PWA cache (104 assets)
const ASSETS_TO_CACHE = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/style.css",
  "./js/app.js",
  "./js/i18n.js",
  "./js/game-engine.js",
  "./js/audio-synth.js",
  "./js/gallery.js",
  "./js/story-timeline.js",
  "./locales/pl.json",
  "./locales/en.json",
  "./assets/reports/anchor_lab.png",
  "./assets/reports/anchor_lab_ch2.png",
  "./assets/reports/anchor_lab_ch3.png",
  "./assets/reports/anchor_lab_ch3_locked.png",
  "./assets/reports/anchor_lab_ch3_solved.png",
  "./assets/reports/movement_lab.png",
  "./assets/reports/station_01.png",
  "./assets/reports/station_01_active.png",
  "./assets/reports/station_02.png",
  "./assets/reports/station_02_correlation.png",
  "./assets/reports/station_03.png",
  "./assets/reports/station_03_desk.png",
  "./assets/reports/station_04.png",
  "./assets/reports/station_04_bramka.png",
  "./assets/reports/station_05.png",
  "./assets/reports/station_05_crosswalk.png",
  "./assets/reports/station_06.png",
  "./assets/reports/station_06_arrival.png",
  "./assets/reports/station_07.png",
  "./assets/reports/station_07_door.png",
  "./assets/reports/station_08.png",
  "./assets/reports/station_08_desk.png",
  "./assets/reports/station_09.png",
  "./assets/reports/station_09_mirror.png",
  "./assets/reports/station_10.png",
  "./assets/reports/station_10_phone.png",
  "./assets/reports/station_11.png",
  "./assets/reports/station_11_intervention.png",
  "./assets/reports/station_12.png",
  "./assets/reports/station_12_terminal.png",
  "./assets/reports/station_13.png",
  "./assets/reports/station_13_photo.png",
  "./assets/reports/station_14.png",
  "./assets/reports/station_14_anchored.png",
  "./assets/reports/station_15.png",
  "./assets/reports/station_15_reflection.png",
  "./assets/reports/station_16.png",
  "./assets/reports/station_16_choice.png",
  "./assets/reports/station_17.png",
  "./assets/reports/station_17_interview.png",
  "./assets/reports/station_18.png",
  "./assets/reports/station_18_interview.png",
  "./assets/reports/station_19.png",
  "./assets/reports/station_19_models.png",
  "./assets/reports/station_20.png",
  "./assets/reports/station_20_szymon.png",
  "./assets/reports/station_21.png",
  "./assets/reports/station_21_szymon.png",
  "./assets/reports/station_22.png",
  "./assets/reports/station_22_yield.png",
  "./assets/reports/station_23.png",
  "./assets/reports/station_23_terminal.png",
  "./assets/reports/station_24.png",
  "./assets/reports/station_24_cctv.png",
  "./assets/reports/station_25.png",
  "./assets/reports/station_25_jakub.png",
  "./assets/reports/station_26.png",
  "./assets/reports/station_26_isolation.png",
  "./assets/reports/station_27.png",
  "./assets/reports/station_27_dialogue.png",
  "./assets/reports/station_28.png",
  "./assets/reports/station_28_transit.png",
  "./assets/reports/station_29.png",
  "./assets/reports/station_29_platform.png",
  "./assets/reports/station_30.png",
  "./assets/reports/station_30_power.png",
  "./assets/reports/station_31.png",
  "./assets/reports/station_31_chairs.png",
  "./assets/reports/station_32.png",
  "./assets/reports/station_32_glass.png",
  "./assets/reports/station_33.png",
  "./assets/reports/station_33_shaft.png",
  "./assets/reports/station_34.png",
  "./assets/reports/station_34_core.png",
  "./assets/reports/station_35.png",
  "./assets/reports/station_35_sedation.png",
  "./assets/reports/station_36.png",
  "./assets/reports/station_36_drain.png",
  "./assets/reports/station_37.png",
  "./assets/reports/station_37_signal.png",
  "./assets/reports/station_38.png",
  "./assets/reports/station_38_rescue.png",
  "./assets/reports/station_39.png",
  "./assets/reports/station_39_triad.png",
  "./assets/reports/station_40.png",
  "./assets/reports/station_40_proposal.png",
  "./assets/reports/station_41.png",
  "./assets/reports/station_41_execution.png",
  "./assets/reports/station_42a.png",
  "./assets/reports/station_42b.png",
  "./assets/reports/station_42c.png",
  "./assets/reports/station_43.png"
];

self.addEventListener("install", event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS_TO_CACHE))
  );
  self.skipWaiting();
});

self.addEventListener("activate", event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.map(key => {
          if (key !== CACHE_NAME) {
            return caches.delete(key);
          }
        })
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", event => {
  event.respondWith(
    caches.match(event.request).then(cachedResponse => {
      if (cachedResponse) {
        return cachedResponse;
      }
      return fetch(event.request).then(networkResponse => {
        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== "basic") {
          return networkResponse;
        }
        const responseToCache = networkResponse.clone();
        caches.open(CACHE_NAME).then(cache => {
          cache.put(event.request, responseToCache);
        });
        return networkResponse;
      });
    })
  );
});
