/**
 * GETTING STRANGE — Service Worker Generator (PKG-0091)
 * Regenerates web/service-worker.js with a full offline asset list:
 * core bundle (HTML/CSS/JS/locales/manifest) + every rendered frame in
 * web/assets/reports. Run after adding/removing assets:
 *   node tools/generate_service_worker.js
 */
const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..");
const webDir = path.join(projectRoot, "web");
const reportsDir = path.join(webDir, "assets", "reports");

const CACHE_VERSION = process.argv[2] || "v3-pkg0091";

const coreAssets = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./css/style.css",
  "./js/app.js",
  "./js/i18n.js",
  "./js/game-engine.js",
  "./js/audio-synth.js",
  "./js/gallery.js",
  "./js/story-timeline.js",
  "./locales/pl.json",
  "./locales/en.json"
];

const reportAssets = fs.readdirSync(reportsDir)
  .filter(f => f.toLowerCase().endsWith(".png"))
  .sort()
  .map(f => `./assets/reports/${f}`);

const allAssets = coreAssets.concat(reportAssets);

const lines = [];
lines.push(`const CACHE_NAME = "getting-strange-${CACHE_VERSION}";`);
lines.push(`// Generated by tools/generate_service_worker.js — full offline PWA cache (${allAssets.length} assets)`);
lines.push("const ASSETS_TO_CACHE = [");
allAssets.forEach((a, i) => {
  lines.push(`  "${a}"${i < allAssets.length - 1 ? "," : ""}`);
});
lines.push("];");
lines.push("");
lines.push('self.addEventListener("install", event => {');
lines.push("  event.waitUntil(");
lines.push("    caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS_TO_CACHE))");
lines.push("  );");
lines.push("  self.skipWaiting();");
lines.push("});");
lines.push("");
lines.push('self.addEventListener("activate", event => {');
lines.push("  event.waitUntil(");
lines.push("    caches.keys().then(keys =>");
lines.push("      Promise.all(");
lines.push("        keys.map(key => {");
lines.push("          if (key !== CACHE_NAME) {");
lines.push("            return caches.delete(key);");
lines.push("          }");
lines.push("        })");
lines.push("      )");
lines.push("    )");
lines.push("  );");
lines.push("  self.clients.claim();");
lines.push("});");
lines.push("");
lines.push('self.addEventListener("fetch", event => {');
lines.push("  event.respondWith(");
lines.push("    caches.match(event.request).then(cachedResponse => {");
lines.push("      if (cachedResponse) {");
lines.push("        return cachedResponse;");
lines.push("      }");
lines.push("      return fetch(event.request).then(networkResponse => {");
lines.push('        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== "basic") {');
lines.push("          return networkResponse;");
lines.push("        }");
lines.push("        const responseToCache = networkResponse.clone();");
lines.push("        caches.open(CACHE_NAME).then(cache => {");
lines.push("          cache.put(event.request, responseToCache);");
lines.push("        });");
lines.push("        return networkResponse;");
lines.push("      });");
lines.push("    })");
lines.push("  );");
lines.push("});");
lines.push("");

fs.writeFileSync(path.join(webDir, "service-worker.js"), lines.join("\n"), "utf8");
console.log(`service-worker.js regenerated: cache getting-strange-${CACHE_VERSION}, ${allAssets.length} assets (${coreAssets.length} core + ${reportAssets.length} report frames)`);
