class_name LocalizationManager
extends RefCounted

## LocalizationManager for Getting Strange (Godot 4.7)
## Handles bilingual runtime localization (PL / EN) with fallback and signal emission.

const SUPPORTED_LOCALES: Array[String] = ["pl", "en"]
static var current_locale: String = "pl"

static var _translations: Dictionary = {
	"pl": {
		"UI_START_EXPERIMENT": "ROZPOCZNIJ POMIAR (21:45)",
		"UI_MOVEMENT_PROFILE": "PROFIL RUCHU:",
		"UI_PROFILE_A": "PROFIL A: BAZOWY (IKP STANDARD)",
		"UI_PROFILE_B": "PROFIL B: SPRĘŻYSTY (SZYBKI)",
		"UI_PROFILE_C": "PROFIL C: INERCYJNY (MASA)",
		"UI_RESTART_HINT": "[R] RESTART KOMORY",
		"UI_ANCHOR_HINT": "[E] ZAKOTWICZENIE  //  [F] KOREKTA",
		"UI_INTERACT_HINT": "[E] INTERAKCJA",
		"TITLE_SUBTITLE": "OSOBISTY THRILLER // POWRÓT PRZEZ LINIĘ 4",
		"TITLE_PERSONAL_PROMISE": "Marta czeka na Lenę. Trzy sekundy z Linii 4 nie chcą zniknąć.",
		"MENU_NEW_GAME": "NOWA GRA",
		"MENU_CONTINUE": "KONTYNUUJ",
		"MENU_REPLAY_EPILOGUE": "POWTÓRZ EPILOG",
		"MENU_SETTINGS": "USTAWIENIA",
		"MENU_QUIT": "ZAKOŃCZ",
		"STATUS_SAVE_ACTIVE": "WZNÓW // %s%s",
		"STATUS_SAVE_NONE": "ZACZNIJ // OSTATNI ODCZYT PRZY LINII 4",
		"STATUS_COMPLETED_SUFFIX": "  //  UKOŃCZONA  //  %s",
		"CONTROLS_HEADER": "RUSZ SIĘ / ZBADAJ",
		"INPUT_ACTION_MOVE_LEFT": "W LEWO",
		"INPUT_ACTION_MOVE_RIGHT": "W PRAWO",
		"INPUT_ACTION_JUMP": "SKOK",
		"INPUT_ACTION_INTERACT": "INTERAKCJA",
		"INPUT_ACTION_PAUSE": "PAUZA",
		"INPUT_ACTION_RESTART": "RESTART",
		"INPUT_ACTION_TRIGGER_CORRECTION": "KOREKTA",
		"BUILD_LABEL": "WER. %s  //  PC  //  %dx%d  //  FIZYKA %d Hz",
		"SETTINGS_TITLE": "USTAWIENIA  //  RUNTIME",
		"SETTINGS_LANGUAGE": "JĘZYK",
		"SETTINGS_LANGUAGE_HINT": "Przełącz teksty shellu i UI.",
		"SETTINGS_MASTER_VOLUME": "GŁOŚNOŚĆ MASTER",
		"SETTINGS_TEXT_SPEED": "TEMPO TEKSTU  //  ZNAKI/S",
		"SETTINGS_TEXT_SCALE": "SKALA TEKSTU",
		"SETTINGS_FULLSCREEN": "TRYB PEŁNOEKRANOWY",
		"SETTINGS_REDUCED_MOTION": "OGRANICZONY RUCH",
		"SETTINGS_REDUCED_MOTION_HINT": "Tłumi migotanie świetlówek, pulsowanie pola kotwiczenia, wstrząs kamery i mikro-cząstki. Nic nie znika ze świata.",
		"SETTINGS_REMAP": "STEROWANIE  //  REMAP",
		"SETTINGS_HINT": "Zmiany zapisują się natychmiast. Dialogi pozostają w języku źródłowym.",
		"SETTINGS_REMAP_TITLE": "STEROWANIE  //  REMAP AKCJI",
		"SETTINGS_REMAP_HINT": "Wybierz akcję, potem naciśnij klawisz lub przycisk pada.",
		"SETTINGS_REMAP_PENDING": "NACIŚNIJ KLAWISZ LUB PRZYCISK PADA DLA: %s\nESC / B = ANULUJ",
		"SETTINGS_REMAP_WAITING": "OCZEKIWANIE…",
		"SETTINGS_REMAP_SAVED": "ZAPISANO: %s",
		"SETTINGS_REMAP_CONFLICT": "KONFLIKT: %s JUŻ UŻYWA TEGO WEJŚCIA",
		"SETTINGS_REMAP_UNSUPPORTED": "TYLKO KLAWISZ LUB PRZYCISK PADA",
		"SETTINGS_RESTORE_DEFAULTS": "DOMYŚLNE MAPOWANIA",
		"SETTINGS_REMAP_DEFAULTS_RESTORED": "PRZYWRÓCONO DOMYŚLNE MAPOWANIA",
		"UI_BACK": "POWRÓT",
		"PAUSE_TITLE": "KAMPANIA  //  PAUZA",
		"PAUSE_RESUME": "WZNÓW",
		"PAUSE_CHECKPOINT": "CHECKPOINT",
		"PAUSE_SETTINGS": "USTAWIENIA",
		"PAUSE_TEST_MODE": "TRYB TESTOWY: %s",
		"PAUSE_RESET_SAVE": "RESET ZAPISU",
		"PAUSE_STATUS": "ODKRYTE: %d/%d   |   TRYB TESTOWY: %s",
		"PAUSE_FOOTER": "PAUZA: POWRÓT  //  INTERAKCJA: WYBÓR",
		"PAUSE_STATION_TOOLTIP": "Adres %s",
		"CRT_CONTINUE": "INTERAKCJA  >",
		"CRT_CHANNEL": "KANAŁ ŚWIADKA  //  ZAPIS AKTYWNY",
		"SAVE_ACTIVE": "ZAPIS AKTYWNY",
		"SAVE_RELOADED": "ZAPIS WCZYTANY",
		"SAVE_RESET": "ZAPIS ZRESETOWANY",
	},
	"en": {
		"UI_START_EXPERIMENT": "START EXPERIMENT (21:45)",
		"UI_MOVEMENT_PROFILE": "MOVEMENT PROFILE:",
		"UI_PROFILE_A": "PROFILE A: BASELINE (IKP STANDARD)",
		"UI_PROFILE_B": "PROFILE B: SNAPPY (FAST)",
		"UI_PROFILE_C": "PROFILE C: INERTIAL (HEAVY)",
		"UI_RESTART_HINT": "[R] RESTART CHAMBER",
		"UI_ANCHOR_HINT": "[E] ANCHOR  //  [F] CORRECTION",
		"UI_INTERACT_HINT": "[E] INTERACT",
		"TITLE_SUBTITLE": "PERSONAL THRILLER // A RETURN ON LINE 4",
		"TITLE_PERSONAL_PROMISE": "Lena is going back to Marta. Three seconds from Line 4 refuse to disappear.",
		"MENU_NEW_GAME": "NEW GAME",
		"MENU_CONTINUE": "CONTINUE",
		"MENU_REPLAY_EPILOGUE": "REPLAY EPILOGUE",
		"MENU_SETTINGS": "SETTINGS",
		"MENU_QUIT": "QUIT",
		"STATUS_SAVE_ACTIVE": "RESUME // %s%s",
		"STATUS_SAVE_NONE": "BEGIN // LAST READING AT LINE 4",
		"STATUS_COMPLETED_SUFFIX": "  //  COMPLETE  //  %s",
		"CONTROLS_HEADER": "MOVE / INVESTIGATE",
		"INPUT_ACTION_MOVE_LEFT": "MOVE LEFT",
		"INPUT_ACTION_MOVE_RIGHT": "MOVE RIGHT",
		"INPUT_ACTION_JUMP": "JUMP",
		"INPUT_ACTION_INTERACT": "INTERACT",
		"INPUT_ACTION_PAUSE": "PAUSE",
		"INPUT_ACTION_RESTART": "RESTART",
		"INPUT_ACTION_TRIGGER_CORRECTION": "CORRECTION",
		"BUILD_LABEL": "VER. %s  //  PC  //  %dx%d  //  %d Hz PHYSICS",
		"SETTINGS_TITLE": "SETTINGS  //  RUNTIME",
		"SETTINGS_LANGUAGE": "LANGUAGE",
		"SETTINGS_LANGUAGE_HINT": "Switch shell and UI text.",
		"SETTINGS_MASTER_VOLUME": "MASTER VOLUME",
		"SETTINGS_TEXT_SPEED": "TEXT SPEED  //  CHARS/S",
		"SETTINGS_TEXT_SCALE": "TEXT SCALE",
		"SETTINGS_FULLSCREEN": "FULLSCREEN MODE",
		"SETTINGS_REDUCED_MOTION": "REDUCED MOTION",
		"SETTINGS_REDUCED_MOTION_HINT": "Damps fluorescent flicker, anchor field breathing, camera shake and micro-particles. Nothing leaves the world.",
		"SETTINGS_REMAP": "CONTROLS  //  REMAP",
		"SETTINGS_HINT": "Changes save immediately. Dialogue remains in its source language.",
		"SETTINGS_REMAP_TITLE": "CONTROLS  //  ACTION REMAP",
		"SETTINGS_REMAP_HINT": "Choose an action, then press a key or controller button.",
		"SETTINGS_REMAP_PENDING": "PRESS A KEY OR CONTROLLER BUTTON FOR: %s\nESC / B = CANCEL",
		"SETTINGS_REMAP_WAITING": "WAITING…",
		"SETTINGS_REMAP_SAVED": "SAVED: %s",
		"SETTINGS_REMAP_CONFLICT": "CONFLICT: %s ALREADY USES THIS INPUT",
		"SETTINGS_REMAP_UNSUPPORTED": "KEY OR CONTROLLER BUTTONS ONLY",
		"SETTINGS_RESTORE_DEFAULTS": "DEFAULT MAPPINGS",
		"SETTINGS_REMAP_DEFAULTS_RESTORED": "DEFAULT MAPPINGS RESTORED",
		"UI_BACK": "BACK",
		"PAUSE_TITLE": "CAMPAIGN  //  PAUSE",
		"PAUSE_RESUME": "RESUME",
		"PAUSE_CHECKPOINT": "CHECKPOINT",
		"PAUSE_SETTINGS": "SETTINGS",
		"PAUSE_TEST_MODE": "TEST MODE: %s",
		"PAUSE_RESET_SAVE": "RESET SAVE",
		"PAUSE_STATUS": "DISCOVERED: %d/%d   |   TEST MODE: %s",
		"PAUSE_FOOTER": "PAUSE: BACK  //  INTERACT: SELECT",
		"PAUSE_STATION_TOOLTIP": "Address %s",
		"CRT_CONTINUE": "INTERACT  >",
		"CRT_CHANNEL": "WITNESS CHANNEL  //  SAVE ACTIVE",
		"SAVE_ACTIVE": "SAVE ACTIVE",
		"SAVE_RELOADED": "SAVE RELOADED",
		"SAVE_RESET": "SAVE RESET",
	}
}


static func set_locale(locale_code: String) -> void:
	if locale_code in SUPPORTED_LOCALES:
		current_locale = locale_code
		TranslationServer.set_locale(locale_code)


static func get_locale() -> String:
	return current_locale


static func tr_key(key: String, fallback: String = "") -> String:
	var dict: Dictionary = _translations.get(current_locale, _translations["pl"])
	if dict.has(key):
		return dict[key]
	var engine_tr: String = TranslationServer.translate(key)
	if engine_tr != "" and engine_tr != key:
		return engine_tr
	return fallback if fallback != "" else key
