[CmdletBinding()]
param(
    [string] $ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [switch] $AllowBinaryBuild
)

$ErrorActionPreference = 'Stop'

Write-Host "== Getting Strange Export Surface Audit =="
$distDir = Join-Path $ProjectRoot "dist"
$windowsDir = Join-Path $distDir "windows"
$linuxDir = Join-Path $distDir "linux"

$godotCommand = (Get-Command godot -ErrorAction Stop).Source
$godotItem = Get-Item -LiteralPath $godotCommand
$godotTarget = [string]$godotItem.Target
if ([string]::IsNullOrWhiteSpace($godotTarget)) {
    $godotTarget = $godotCommand
}

$consoleCandidate = Join-Path (Split-Path -Parent $godotTarget) (([System.IO.Path]::GetFileNameWithoutExtension($godotTarget)) + '_console.exe')
$godot = if (Test-Path -LiteralPath $consoleCandidate) { $consoleCandidate } else { $godotTarget }
$godotVersion = (& $godot --version | Select-Object -First 1).Trim()
$godotVersionMatch = [regex]::Match($godotVersion, '^(?<version>\d+\.\d+\.\d+)\.(?<flavor>[A-Za-z0-9]+)')
if (-not $godotVersionMatch.Success) {
    throw "Cannot derive export template identifier from Godot version '$godotVersion'"
}

$templateVersion = $godotVersionMatch.Groups['version'].Value
$templateFlavor = $godotVersionMatch.Groups['flavor'].Value
$templateId = "$templateVersion.$templateFlavor"
$templateDir = Join-Path $env:APPDATA "Godot/export_templates/$templateId"
$requiredTemplateFiles = @(
    'windows_debug_x86_64.exe',
    'windows_release_x86_64.exe',
    'linux_debug.x86_64',
    'linux_release.x86_64'
)
$forbiddenExportRoots = @(
    'res://tests/',
    'res://tools/',
    'res://docs/',
    'res://godot-mcp/',
    'res://vibe-eyes/',
    'res://reports/',
    'res://snapshots/',
    'res://archive_retired_web/',
    'res://playtest_panel_2026-08-25/',
    'res://scripts/levels/logs/',
    'res://skills/',
    'res://.claude/',
    'res://.codex/',
    'res://.omp/'
)

function Ensure-ExportTemplates {
    param(
        [string] $InstallDir,
        [string] $Version,
        [string] $Flavor,
        [string[]] $RequiredFiles
    )

    $missing = @($RequiredFiles | Where-Object { -not (Test-Path -LiteralPath (Join-Path $InstallDir $_)) })
    if ($missing.Count -eq 0) {
        Write-Host "Export templates present: $InstallDir"
        return
    }

    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    $archiveName = "Godot_v{0}-{1}_export_templates.tpz" -f $Version, $Flavor
    $archivePath = Join-Path $env:TEMP $archiveName
    $downloadUrl = "https://downloads.godotengine.org/?version={0}&flavor={1}&slug=export_templates.tpz&platform=templates" -f $Version, $Flavor

    Write-Host "Missing export templates for ${templateId}: $($missing -join ', ')"
    Write-Host "Downloading official standard export templates from $downloadUrl"
    Invoke-WebRequest -Uri $downloadUrl -OutFile $archivePath

    Write-Host "Installing export templates into $InstallDir"
    tar -xf $archivePath -C $InstallDir --strip-components 1 templates

    $missingAfterInstall = @($RequiredFiles | Where-Object { -not (Test-Path -LiteralPath (Join-Path $InstallDir $_)) })
    if ($missingAfterInstall.Count -gt 0) {
        throw "Export templates still missing after install: $($missingAfterInstall -join ', ')"
    }
}

function Invoke-VerifiedGodotExport {
    param(
        [string] $PresetName,
        [string] $OutputPath
    )

    $lines = & $godot --headless --path $ProjectRoot --export-release $PresetName $OutputPath 2>&1 | ForEach-Object { $_.ToString() }
    foreach ($line in $lines) {
        Write-Host $line
    }
    if ($LASTEXITCODE -ne 0) {
        throw "$PresetName export failed with exit code $LASTEXITCODE"
    }

    $forbiddenHits = foreach ($root in $forbiddenExportRoots) {
        $matches = @($lines | Where-Object { $_ -like "*$root*" })
        if ($matches.Count -gt 0) {
            $matches
        }
    }
    $forbiddenHits = @($forbiddenHits | Sort-Object -Unique)
    if ($forbiddenHits.Count -gt 0) {
        Write-Host "Forbidden export surface detected:"
        foreach ($hit in $forbiddenHits) {
            Write-Host " - $hit"
        }
        throw "Forbidden export surface detected for preset '$PresetName'"
    }
}

Write-Host "Godot executable: $godot"
Write-Host "Godot version: $godotVersion"

if (-not $AllowBinaryBuild) {
    Write-Host "D-125 guard: Binary build blocked."
    Write-Host "No new .exe, .x86_64 or distribution artifact will be generated by default."
    if (Test-Path -LiteralPath $distDir) {
        Write-Host "Historical dist/ artifacts present (not evidence of current release readiness):"
        Get-ChildItem -Path $distDir -Recurse -File | Select-Object FullName, LastWriteTime, Length | ForEach-Object {
            $sizeMb = [math]::Round($_.Length / 1MB, 2)
            Write-Host " - $($_.FullName) | $($_.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss')) | $sizeMb MB"
        }
    } else {
        Write-Host "No dist/ directory present."
    }
    Write-Host "Re-run with -AllowBinaryBuild only inside an explicitly authorized release package."
    return
}

Ensure-ExportTemplates -InstallDir $templateDir -Version $templateVersion -Flavor $templateFlavor -RequiredFiles $requiredTemplateFiles

Write-Host "Binary build authorized for this run."
New-Item -ItemType Directory -Force -Path $windowsDir | Out-Null
New-Item -ItemType Directory -Force -Path $linuxDir | Out-Null

Write-Host "Exporting Windows Desktop release..."
$winExe = Join-Path $windowsDir "GettingStrange.exe"
Invoke-VerifiedGodotExport -PresetName "Windows Desktop" -OutputPath $winExe
Get-ChildItem -Path $windowsDir -Filter "*.tmp" -ErrorAction SilentlyContinue | Remove-Item -Force

Write-Host "Exporting Linux Desktop release..."
$linuxBin = Join-Path $linuxDir "GettingStrange.x86_64"
Invoke-VerifiedGodotExport -PresetName "Linux Desktop" -OutputPath $linuxBin
Get-ChildItem -Path $linuxDir -Filter "*.tmp" -ErrorAction SilentlyContinue | Remove-Item -Force

Write-Host "== Export Summary =="
Get-ChildItem -Path $distDir -Recurse -File | Select-Object FullName, Length | ForEach-Object {
    $sizeMb = [math]::Round($_.Length / 1MB, 2)
    Write-Host " - $($_.FullName) ($sizeMb MB)"
}

Write-Host "Export completed successfully."
